import type { ReactNode } from 'react';
import type { PlanetPreview } from '@megaplanets/planet-generator';
import { drawingStatusLabel } from '@/hooks/usePlanetDrawingStates';
import type { RoundStatus } from '@/lib/api';
import { PlanetThumbnail } from './PlanetThumbnail';

export function PlanetInventoryDetail({ preview, revealed, drawingStatus, mintAction }: { preview: PlanetPreview; revealed: boolean; drawingStatus: RoundStatus | undefined; mintAction: ReactNode }) {
  if (!revealed) {
    return <section className="rounded-[20px] border border-[var(--border-strong)] bg-[var(--surface-raised)] p-5"><p className="telemetry text-[var(--text-primary)]">{drawingStatusLabel(drawingStatus)}</p><div className="mt-5 [&>div>p]:hidden [&>div>button]:w-full">{mintAction}</div></section>;
  }

  const { descriptor } = preview;
  return <section className="rounded-[20px] border border-[var(--border-strong)] bg-[var(--surface-raised)] p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="telemetry text-[var(--rare)]">{descriptor.traits.type}</p><h1 className="mt-1 font-hud text-4xl font-bold tracking-[-0.05em] text-[var(--text-primary)]">{descriptor.traits.name}</h1></div><p className="telemetry rounded-full border border-[var(--border)] px-3 py-2 text-[var(--text-secondary)]">{drawingStatusLabel(drawingStatus)}</p></div><div className="mt-5 overflow-hidden rounded-[14px] border border-[var(--border)] bg-[var(--surface)]"><PlanetThumbnail descriptor={preview.visual} /></div><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-[var(--surface)] p-3"><dt className="telemetry text-[var(--text-secondary)]">MINERALS</dt><dd className="mt-1 font-hud text-lg font-bold text-[var(--text-primary)]">{descriptor.traits.minerals} minerals/day</dd></div><div className="rounded-xl bg-[var(--surface)] p-3"><dt className="telemetry text-[var(--text-secondary)]">RARITY</dt><dd className="mt-1 font-hud text-lg font-bold text-[var(--text-primary)]">{descriptor.traits.rarity}</dd></div><div className="rounded-xl bg-[var(--surface)] p-3"><dt className="telemetry text-[var(--text-secondary)]">SATELLITES</dt><dd className="mt-1 font-hud text-lg font-bold text-[var(--text-primary)]">{descriptor.traits.satelliteCount}{descriptor.traits.hasRing ? ' / ring' : ''}</dd></div><div className="rounded-xl bg-[var(--surface)] p-3"><dt className="telemetry text-[var(--text-secondary)]">TICKET</dt><dd className="mt-1 font-hud text-lg font-bold text-[var(--text-primary)]">#{descriptor.input.ticketId.toString()}</dd></div></dl><div className="mt-5 border-t border-[var(--border)] pt-4"><p className="font-mono text-sm text-[var(--text-primary)]">{descriptor.input.normals.join(' / ')} + {descriptor.input.bonusBall}</p><dl className="mt-4 space-y-3 text-xs"><div><dt className="telemetry text-[var(--text-secondary)]">SEED</dt><dd className="mt-1 break-all font-mono text-[var(--text-primary)]">{descriptor.seed}</dd></div><div><dt className="telemetry text-[var(--text-secondary)]">TRAITS HASH</dt><dd className="mt-1 break-all font-mono text-[var(--text-primary)]">{descriptor.traitsHash}</dd></div></dl></div></section>;
}
